# Generated by Django 4.1.4 on 2023-07-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0077_alter_daily_leeds_exists_date_dmwarningmails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DMWarningMails',
        ),
    ]
