# Generated by Django 4.1.4 on 2023-07-05 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0079_dm_warning_mails'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='achived',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='daily_leeds_exists',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 5)),
        ),
    ]
