# Generated by Django 4.1.4 on 2023-07-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0080_work_achived_alter_daily_leeds_exists_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm_warning_mails',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.work'),
        ),
    ]
