# Generated by Django 4.1.4 on 2023-07-06 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0081_dm_warning_mails_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='warning_mail',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='daily_leeds_exists',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 6)),
        ),
    ]
